### ISSUE TITLE
单个图的微调功能

### ISSUE THREAD

**Issue by 1120158440** [mouxangithub/plugin_midjourney#10]
![06ee929905cbc2b34654f758a27d64a](https://github.com/mouxangithub/midjourney-proxy-on-wechat/assets/37127239/69621d17-2d61-4d5d-945d-a5e42e9c83c8)
能把这些 加上去么? 强变化, 微变化 缩放比例  这些

**Comment by mouxangithub** [comment]
midjourney-proxy免费版已经不更新了，搞了个midjourney-proxy-plus付费版要钱，作者没钱喝茶进不去这个项目，后续打算用midjourney-api进行重构这项服务就包含了这些功能，稍安勿躁，可能没那么快，作者需要工作
https://github.com/erictik/midjourney-api
