### ISSUE TITLE
在垫图与混图时遇到异常，在midjourney-proxy中报错日志如下

### ISSUE THREAD

**Issue by RolloTomasiii** [mouxangithub/plugin_midjourney#11]
2023-07-27 13:43:24.182  WARN 1 --- [  ReadingThread] c.g.n.m.wss.handle.ErrorMessageHandler   : 检测到可能异常的信息: Invalid link
Could not validate this link. Please try again later.
footer: /imagine https://cdn.discordapp.com/ephemeral-attachments/1062880************/113399804************/0358489054808711.null https://cdn.discordapp.com/ephemeral-attachments/106288010************/1133998045************/0358489054808711.null --ar 1:1
2023-07-27 13:43:24.184 DEBUG 1 --- [    TaskQueue-3] c.g.n.m.support.TaskQueueHelper          : task finished, id: 0358489054808711, status: FAILURE

**Comment by mouxangithub** [comment]
应该是图片没上传完就立马发送了/e，图片地址为.null

**Comment by RolloTomasiii** [comment]
> 

那在哪里加个睡眠比较合适

**Comment by RolloTomasiii** [comment]
> 应该是图片没上传完就立马发送了/e，图片地址为.null
那在哪里加个睡眠比较合适

**Comment by RolloTomasiii** [comment]
> 

那在哪里加个睡眠比较合适

**Comment by RolloTomasiii** [comment]
> 应该是图片没上传完就立马发送了/e，图片地址为.null

那在哪里加个睡眠比较合适

**Comment by RolloTomasiii** [comment]
可是我把那个链接的后缀改成.png后就得到我上传的那个图了，有没有可能是代码少个后缀

**Comment by RolloTomasiii** [comment]
刚刚我测试了，上传完图片后等了一会儿还是 .null，应该不是上传没结束的问题

**Comment by mouxangithub** [comment]
得一一对应，上传完一张图就有一条消息回复就证明拿到了

**Comment by RolloTomasiii** [comment]
> 得一一对应，上传完一张图就有一条消息回复就证明拿到了

我就是等他回复了，才上传另一张的

**Comment by mouxangithub** [comment]
> > 得一一对应，上传完一张图就有一条消息回复就证明拿到了
> 
> 我就是等他回复了，才上传另一张的

mj-proxy是最新版么，我这边没出现过这种情况

**Comment by RolloTomasiii** [comment]
> > > 得一一对应，上传完一张图就有一条消息回复就证明拿到了
> > 
> > 
> > 我就是等他回复了，才上传另一张的
> 
> mj-proxy是最新版么，我这边没出现过这种情况

是最新的

**Comment by RolloTomasiii** [comment]
会不会是cdn.discordapp.com开了代理的原因
