### ISSUE TITLE
多人同时请求时，任务超时

### ISSUE THREAD

**Issue by Neph0s** [mouxangithub/plugin_midjourney#12]
如题，2个用户同时请求时，会有一个用户的任务出现超时。
discord端两个任务都出图了，但微信端第二个任务会超时。

**Comment by mouxangithub** [comment]
这跟你的账号限制有关，可以修改proxy的超时时间，账号是共享账号多人使用就会一直处于排队最后导致超时
我的文档上有说明
https://github.com/mouxangithub/midjourney-proxy-on-wechat#%E4%B8%80%E4%BA%9B%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E%E4%BB%A5%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
