### ISSUE TITLE
请问下这是什么报错

### ISSUE THREAD

**Issue by ymeimei** [mouxangithub/plugin_midjourney#13]
[ERROR][2023-08-01 09:52:51][mjapi.py:61] - 'code'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chat\plugins\midjourney\mjapi.py", line 59, in imagine
    return self.subTip(res)
  File "C:\Users\Administrator\Desktop\chat\plugins\midjourney\mjapi.py", line 36, in subTip
    code = rj["code"]
KeyError: 'code'
[INFO][2023-08-01 09:52:51][wechat_channel.py:186] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
❌ 任务提交失败), receiver=@691d174cf62e803b95fafe1de3b3f8f04761e0c101dc686024f9e8d391ff7467

**Comment by mouxangithub** [comment]
服务起来了么，没请求成功

**Comment by ymeimei** [comment]
> 服务起来了么，没请求成功

网站能访问到，我用的zeabur部署，日志里面构建记录有，运行记录没有

**Comment by mouxangithub** [comment]
> > 服务起来了么，没请求成功
> 
> 网站能访问到，我用的zeabur部署，日志里面构建记录有，运行记录没有

进那个网站也就是api文档调试下接口看看出的结果

**Comment by ymeimei** [comment]
> > > 服务起来了么，没请求成功
> > 
> > 
> > 网站能访问到，我用的zeabur部署，日志里面构建记录有，运行记录没有
> 
> 进那个网站也就是api文档调试下接口看看出的结果

奇怪，调试显示可以请求成功{
  "code": 1,
  "description": "提交成功",
  "result": "0452164493055063",
  "properties": {}
}

**Comment by mouxangithub** [comment]
> > > > 服务起来了么，没请求成功
> > > 
> > > 
> > > 网站能访问到，我用的zeabur部署，日志里面构建记录有，运行记录没有
> > 
> > 
> > 进那个网站也就是api文档调试下接口看看出的结果
> 
> 奇怪，调试显示可以请求成功{ "code": 1, "description": "提交成功", "result": "0452164493055063", "properties": {} }

那可能是跨域或者需要代理

**Comment by ymeimei** [comment]
> > > > > 服务起来了么，没请求成功
> > > > 
> > > > 
> > > > 网站能访问到，我用的zeabur部署，日志里面构建记录有，运行记录没有
> > > 
> > > 
> > > 进那个网站也就是api文档调试下接口看看出的结果
> > 
> > 
> > 奇怪，调试显示可以请求成功{ "code": 1, "description": "提交成功", "result": "0452164493055063", "properties": {} }
> 
> 那可能是跨域或者需要代理

代理设置过也是不行，那可能就是跨域了
