### ISSUE TITLE
输入$mj_help指令时报错，求大佬指点

### ISSUE THREAD

**Issue by bluecc0** [mouxangithub/plugin_midjourney#17]
railway平台部署，依次完成到#scanp扫描出插件MidJourney_v1.0.45
在输入$mj_help报错如下
`[ERROR][2023-08-04 14:38:15][chat_channel.py:270] - Worker return exception: '_mjApi' object has no attribute 'reroll_prefix'
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
﻿result = self.fn(*self.args, **self.kwargs)
﻿File "/app/channel/chat_channel.py", line 146, in _handle
﻿reply = self._generate_reply(context)
﻿File "/app/channel/chat_channel.py", line 156, in _generate_reply
﻿e_context = PluginManager().emit_event(
﻿File "/app/plugins/plugin_manager.py", line 189, in emit_event
﻿instance.handlers[e_context.event](e_context, *args, **kwargs)
﻿File "/app/plugins/midjourney/midjourney.py", line 168, in on_handle_context
﻿return self.handle_command(e_context)
﻿File "/app/plugins/midjourney/midjourney.py", line 346, in handle_command
﻿return Info(get_help_text(self, verbose=True), e_context)
﻿File "/app/plugins/midjourney/ctext.py", line 381, in get_help_text
﻿help_text = self.mj.help_text()
﻿File "/app/plugins/midjourney/mjapi.py", line 320, in help_text
﻿help_text += f"(8) reroll重新生成:使用['{self.reroll_prefix[0]}' + 任务ID操作]即可重新绘制图片\n"
﻿AttributeError: '_mjApi' object has no attribute 'reroll_prefix'`

在输入/mj a dog生成图片时报错
`[INFO][2023-08-04 14:39:18][midjourney.py:832] - [MJ] /imagine prompt=a dog imgList=[]
﻿[ERROR][2023-08-04 14:39:46][mjapi.py:61] - HTTPSConnectionPool(host='midjourney-proxy-******.railway.app', port=8080): Max retries exceeded with url: /mj/submit/imagine (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f25013e9e70>, 'Connection to midjourney-proxy-******.railway.app timed out. (connect timeout=None)'))
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
﻿conn = connection.create_connection(
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
﻿raise err
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
﻿sock.connect(sa)
﻿TimeoutError: [Errno 110] Connection timed out
﻿During handling of the above exception, another exception occurred:
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
﻿httplib_response = self._make_request(
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
﻿self._validate_conn(conn)
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
﻿conn.connect()
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
﻿self.sock = conn = self._new_conn()
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
﻿raise ConnectTimeoutError(
﻿urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f25013e9e70>, 'Connection to midjourney-proxy-******.railway.app timed out. (connect timeout=None)')
﻿During handling of the above exception, another exception occurred:
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
﻿resp = conn.urlopen(
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
﻿retries = retries.increment(
﻿File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
﻿raise MaxRetryError(_pool, url, error or ResponseError(cause))
﻿urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='midjourney-proxy-******.railway.app', port=8080): Max retries exceeded with url: /mj/submit/imagine (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f25013e9e70>, 'Connection to midjourney-proxy-******.railway.app timed out. (connect timeout=None)'))
﻿During handling of the above exception, another exception occurred:
﻿Traceback (most recent call last):
﻿File "/app/plugins/midjourney/mjapi.py", line 58, in imagine
﻿res = requests.post(url, json=data, headers=self.headers)
﻿File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
﻿return request("post", url, data=data, json=json, **kwargs)
﻿File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
﻿return session.request(method=method, url=url, **kwargs)
﻿File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
﻿resp = self.send(prep, **send_kwargs)
﻿File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
﻿r = adapter.send(request, **kwargs)
﻿File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
﻿raise ConnectTimeout(e, request=request)
﻿requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='midjourney-proxy-******.railway.app', port=8080): Max retries exceeded with url: /mj/submit/imagine (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f25013e9e70>, 'Connection to midjourney-proxy-******.railway.app timed out. (connect timeout=None)'))
﻿[INFO][2023-08-04 14:39:47][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
﻿❌ 任务提交失败), receiver=@a633b1567733278781cee4a856c616d3251ff16b125a4c8624aba8eafcbf7e33`

**Comment by mouxangithub** [comment]
新增了个reroll_prefix重新生成指令没配
