### ISSUE TITLE
用户每日上限的逻辑似乎有点问题。

### ISSUE THREAD

**Issue by befantasy** [mouxangithub/plugin_midjourney#19]
用户达到图片生成限制后，正常发文字也会提示”次数用完“。
把mj插件的priority设置成-1也无济于事。
应该只有触发词触发作图的prompt受到限制，不含触发词的prompt应该跳过啊。

![39fa4646ae26229f6791b9c2c44ea61](https://github.com/mouxangithub/midjourney-proxy-on-wechat/assets/31535803/07eb1535-4b84-4f7d-b75f-3d95bc23518b)

**Comment by mouxangithub** [comment]
了解，将在下一个版本优化这个问题，
