### ISSUE TITLE
$mj_help指令之后报错

### ISSUE THREAD

**Issue by bluecc0** [mouxangithub/plugin_midjourney#20]
railway部署，求指教﻿
插件扫描完成
﻿发现新插件：
﻿MidJourney_v1.0.46), receiver=@5d3e2bbc70e2a09a403d1390607189f48009e5de28c790a7a4f24932ed3ab810
﻿[ERROR][2023-08-07 11:31:22][chat_channel.py:270] - Worker return exception: '@5d3e2bbc70e2a09a403d1390607189f48009e5de28c790a7a4f24932ed3ab810'
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
﻿result = self.fn(*self.args, **self.kwargs)
﻿File "/app/channel/chat_channel.py", line 146, in _handle
﻿reply = self._generate_reply(context)
﻿File "/app/channel/chat_channel.py", line 156, in _generate_reply
﻿e_context = PluginManager().emit_event(
﻿File "/app/plugins/plugin_manager.py", line 189, in emit_event
﻿instance.handlers[e_context.event](e_context, *args, **kwargs)
﻿File "/app/plugins/midjourney/midjourney.py", line 167, in on_handle_context
﻿self.userInfo = self.get_user_info(e_context)
﻿File "/app/plugins/midjourney/midjourney.py", line 884, in get_user_info
﻿if "mj_data" not in self.user_datas[uid] or (self.user_datas[uid]["mj_data"] and self.user_datas[uid]["mj_data"]["time"] != current_date):
﻿KeyError: '@5d3e2bbc70e2a09a403d1390607189f48009e5de28c790a7a4f24932ed3ab810'

**Comment by mouxangithub** [comment]
> railway部署，求指教﻿ 插件扫描完成 ﻿发现新插件： ﻿MidJourney_v1.0.46), receiver=@5d3e2bbc70e2a09a403d1390607189f48009e5de28c790a7a4f24932ed3ab810 ﻿[ERROR][2023-08-07 11:31:22][chat_channel.py:270] - Worker return exception: '@5d3e2bbc70e2a09a403d1390607189f48009e5de28c790a7a4f24932ed3ab810' ﻿Traceback (most recent call last): ﻿File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run ﻿result = self.fn(*self.args, **self.kwargs) ﻿File "/app/channel/chat_channel.py", line 146, in _handle ﻿reply = self._generate_reply(context) ﻿File "/app/channel/chat_channel.py", line 156, in _generate_reply ﻿e_context = PluginManager().emit_event( ﻿File "/app/plugins/plugin_manager.py", line 189, in emit_event ﻿instance.handlers[e_context.event](e_context, *args, **kwargs) ﻿File "/app/plugins/midjourney/midjourney.py", line 167, in on_handle_context ﻿self.userInfo = self.get_user_info(e_context) ﻿File "/app/plugins/midjourney/midjourney.py", line 884, in get_user_info ﻿if "mj_data" not in self.user_datas[uid] or (self.user_datas[uid]["mj_data"] and self.user_datas[uid]["mj_data"]["time"] != current_date): ﻿KeyError: '@5d3e2bbc70e2a09a403d1390607189f48009e5de28c790a7a4f24932ed3ab810'

已经修复发了个新版本
