### ISSUE TITLE
blend混图的使用逻辑可以简化成：混图命令 + 混图数量》发送相应数量的图片》开始混图。

### ISSUE THREAD

**Issue by befantasy** [mouxangithub/plugin_midjourney#21]
现在的使用逻辑是：混图命令》发送多张图片》发送结束提示符触发混图任务。
是否可以简化成：混图命令 + 图片数量》发送相应数量的图片，数量达到后自动触发混图任务。

**Comment by mouxangithub** [comment]
这个可以自行修改的，因为混图是多张，没法辨别需要几张，你可以自行修改源码

**Comment by befantasy** [comment]
我的意思是：输入 /b 3 ，就是告诉插件混3张，一旦发够3张就开始混图。输入 /b 2，就等待用户发够2张开始混图。这样就可以省去输入/e的步骤，简化一次输入，三步变两步。

**Comment by mouxangithub** [comment]
> 我的意思是：输入 /b 3 ，就是告诉插件混3张，一旦发够3张就开始混图。输入 /b 2，就等待用户发够2张开始混图。这样就可以省去输入/e的步骤，简化一次输入，三步变两步。

/b后会有一个dimensions比例参数
