### ISSUE TITLE
私聊窗口直接发送图片就会触发describe命令，可否增加一个开关或者也需要命令才能触发

### ISSUE THREAD

**Issue by ladypiapia** [mouxangithub/plugin_midjourney#23]
因为我是直接用主账号作为机器人，有时候和朋友聊天发图也会直接触发这个命令，导致不太方便，可否设置一个开关或者也需要命令才能触发这个图生文功能

**Comment by mouxangithub** [comment]
有describe_prefix指令配置，但默认私聊发图片也会触发，你可以修改midjourney-proxy-on-wechat
/midjourney.py下的识图代码将之注释掉即可，后续我看看加个私聊窗口触发识图的开关
![1691994168729](https://github.com/mouxangithub/midjourney-proxy-on-wechat/assets/48978046/944ba75f-5fc1-4fe0-acae-893ca57c0ec1)
