### ISSUE TITLE
 discord反代地址问题 以及 图片画质损耗问题

### ISSUE THREAD

**Issue by TGap-Ruo** [mouxangithub/plugin_midjourney#24]
（1） discord反代地址问题
想问下大佬是否有别的https://cdn.discordapp.com/  反代地址使图片可以不使用科学上网就可以访问
（2）图片画质损耗问题
通过[chatgpt-on-wechat](https://github.com/zhayujie/chatgpt-on-wechat)项目发送到微信的照片存在严重的画质损耗，个人推测是否是因为代码问题导致itchat未发送原图，想问问是否有解决方法

**Comment by mouxangithub** [comment]
> （1） discord反代地址问题 想问下大佬是否有别的https://cdn.discordapp.com/ 反代地址使图片可以不使用科学上网就可以访问 （2）图片画质损耗问题 通过[chatgpt-on-wechat](https://github.com/zhayujie/chatgpt-on-wechat)项目发送到微信的照片存在严重的画质损耗，个人推测是否是因为代码问题导致itchat未发送原图，想问问是否有解决方法

1.没别的办法，只能用代理或者用国外的服务器部署
2.发送的是原图，画图的时候可以调节画质参数那些，具体自己看mj文档

**Comment by lei195827** [comment]
楼主现在解决这个办法没？我试图用cf反代还是没法访问
