### ISSUE TITLE
每次正常聊天的时候，也会触发midjourney插件回复

### ISSUE THREAD

**Issue by fatwang2** [mouxangithub/plugin_midjourney#25]
正常的聊天回复中，该插件也会回复一大段个人信息，插件的优先级我已经调整为-1了，按理说不应该有这种情况

[INFO][2023-09-03 11:49:08][midjourney.py:883]

**Comment by fatwang2** [comment]
看了下，回复的全部都是user_data的内容，要如何理解？

**Comment by mouxangithub** [comment]
有图么，不太理解你的意思
