### ISSUE TITLE
大佬，求救，要哭了，弄了好几天了，始终卡在一个环节，能请教一下么？

### ISSUE THREAD

**Issue by iceiccy** [mouxangithub/plugin_midjourney#26]
大佬，我别的都完成了，就始终卡在一个错误，不管如何修改，GPT和claude都快秃皮了，实在搞不定了，一直提示[ERROR][2023-09-12 19:17:37][chat_channel.py:280] - Worker return exception: '_mjApi' object has no attribute 'reroll_prefix'，我实在无能为力了，你能救救我么？我也联系不上您，如果您看到我的求救了，可以加我V，lylsfei，感谢您，我实在绷不住了

**Comment by mouxangithub** [comment]
修复了，重新安装下

**Comment by iceiccy** [comment]
我现在chatgpt-on-wechat+midjourney-proxy+midjourney-proxy-on-wechat都安装成功了，输入mj_help也能正确返回，但是只要一画图，就提示：
[ERROR]
❌ 任务提交失败，错误代码是：[INFO][2023-09-14 21:30:58][midjourney.py:841] - [MJ] /imagine prompt=汽车 imgList=[]
[ERROR][2023-09-14 21:30:59][mjapi.py:62] - 'code'
Traceback (most recent call last):
  File "C:\Kevin\Cow\plugins\midjourney\mjapi.py", line 60, in imagine
    return self.subTip(res)
           ^^^^^^^^^^^^^^^^
  File "C:\Kevin\Cow\plugins\midjourney\mjapi.py", line 37, in subTip
    code = rj["code"]
           ~~^^^^^^^^
KeyError: 'code'
[INFO][2023-09-14 21:31:00][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
❌ 任务提交失败), receiver=@63c8d98b4361299b6f777af878874045a5365251bf8521b4e3fba12a78accbf9
虽然提示是mjapi.py的问题，但我想是不是
"mj_url": "",
"mj_api_secret": "",
"discordapp_proxy": "",
设置的问题，除了第一个url我知道怎么填，剩下的俩我实在不知道了，三个晚上了，想哭，作者大大，能请教一下你么？就差最后一步了，哭死QAQ
