### ISSUE TITLE
个人微信-垫图模式下收不到图片+个人企微下收不到返回图片

### ISSUE THREAD

**Issue by fatwang2** [mouxangithub/plugin_midjourney#29]
个人微信：垫图模式下长时间收不到图片
![image](https://github.com/mouxangithub/midjourney-proxy-on-wechat/assets/134143178/87689b04-ecea-4161-85bb-cbd7242d5b69)

个人企微：没有正常返回图片内容，只返回了成功的通知
![image](https://github.com/mouxangithub/midjourney-proxy-on-wechat/assets/134143178/5721aab5-cfca-4bb3-97d7-552ac9010a8d)

**Comment by LeaveC** [comment]
我也是有同样的问题，企微也收不到返回图片
![image](https://github.com/mouxangithub/midjourney-proxy-on-wechat/assets/69228332/5a934668-5fdb-4f61-890d-809f57259c1f)

**Comment by fatwang2** [comment]
请问这个问题应该怎么处理呀？ @mouxangithub

**Comment by mouxangithub** [comment]
用国外的服务器或者开代理

**Comment by fatwang2** [comment]
我的服务器是国外的，itchat 通道下垫图走不通，正常画图是可用的。我试过另外一个 mj的插件可以用垫图，不知道哪里有问题

Johnathan Abts ***@***.***>于2023年9月27日 周三05:06写道：
