### ISSUE TITLE
is_domain_name 不支持http地址

### ISSUE THREAD

**Issue by 1120158440** [mouxangithub/plugin_midjourney#4]
这个方法里面的正则支持https 导致http地址设置上去后就会为置空 mj_url设置不上去

**Comment by mouxangithub** [comment]
我试了并未复现你这种情况，应该是域名标点符号没输对可能会导致没检测通过is_domain_name然后清空mj_url，我试了http://还是https://都是可以的

**Comment by 1120158440** [comment]
我设置得是 http://127.0.0.1:8080  这个校验没过。  我最后直接把这个方法判断直接改成true了

**Comment by mouxangithub** [comment]
嗯，确实，ip加端口忘了兼容了，新版已经发布了，重新拉取再试试
