### ISSUE TITLE
经常会提示超时，mj代理的项目日志有提示绘制进度

### ISSUE THREAD

**Issue by 1120158440** [mouxangithub/plugin_midjourney#6]
![image](https://github.com/mouxangithub/midjourney/assets/37127239/0edbf96b-d137-4674-88ac-cd84056371d8)
![image](https://github.com/mouxangithub/midjourney/assets/37127239/10c68bfb-0aec-49e1-9987-23b27beb4ae0)

超时问题解决方案：
首先在discord输入/info查看你的`Fast Time Remaining`快速出图时间，然后我了解到有些朋友的是某宝某鱼上租的共享账号，这类账号的特点问题就是人多使用，加上上面的快速出图时间可能用完了，造成了你提交的作图一直在排队中，针对这类问题的解决方案如下：首先将midjourney-proxy更新到最新版，然后在他的配置项里面有一个`mj.queue.timeout-minutes`配置，即为任务超时时间，默认是五分钟，由于你的是多人使用的账号，所以次数可以延长些，改到十分钟甚至更长，具体自己试试，如果是专业版的话还可以修改`mj.queue.core-size`和`mj.queue.queue-size`并发数和等待队列长度，具体参考[`MidJourney订阅级别`](https://docs.midjourney.com/docs/plans)

**Comment by mouxangithub** [comment]
MJ代理需要用一些特殊手段进行魔法加速，国内服务器会经常提示超时，这个插件也无法解决

**Comment by 1120158440** [comment]
能教下怎么避免出现么？

**Comment by 1120158440** [comment]
有些提示词我用的好好的  有些提示词我怎么画 都可以出图，有些提示词 就会出不来 ，有些就会提示超时，不懂诶

**Comment by mouxangithub** [comment]
mj提示词好像有字数要求，我看你的好像过长了，加上传输这么多可能就导致超时了，mj-proxy也开始收费了，新功能它不会更新，回头打算用mj-api重构一个服务

**Comment by Neph0s** [comment]
> MJ代理需要用一些特殊手段进行魔法加速，国内服务器会经常提示超时，这个插件也无法解决

我的服务器是境外的，也会显示“任务超时”。我看了下discord前端，图片是有画出来的，就是没传回来。请问这个怎么处理呀。

**Comment by Neph0s** [comment]
需要在midjourney-proxy那设置user-wss=False并使用bot吗？

**Comment by mouxangithub** [comment]
> > MJ代理需要用一些特殊手段进行魔法加速，国内服务器会经常提示超时，这个插件也无法解决
> 
> 我的服务器是境外的，也会显示"任务超时"。我看了下discord前端，图片是有画出来的，就是没传回来。请问这个怎么处理呀。

·超时问题：首先在discord输入/info查看你的Fast Time Remaining快速出图时间，然后我了解到有些朋友的是某宝某鱼上租的共享账号，这类账号的特点问题就是人多使用，加上上面的快速出图时间可能用完了，造成了你提交的作图一直在排队中，针对这类问题的解决方案如下：首先将midjourney-proxy更新到最新版，然后在他的配置项里面有一个mj.queue.timeout-minutes配置，即为任务超时时间，默认是五分钟，由于你的是多人使用的账号，所以次数可以延长些，改到十分钟甚至更长，具体自己试试，如果是专业版的话还可以修改mj.queue.core-size和mj.queue.queue-size并发数和等待队列长度，具体参考MidJourney订阅级别 https://docs.midjourney.com/docs/plans

**Comment by Neph0s** [comment]
> > > MJ代理需要用一些特殊手段进行魔法加速，国内服务器会经常提示超时，这个插件也无法解决
> > 
> > 
> > 我的服务器是境外的，也会显示"任务超时"。我看了下discord前端，图片是有画出来的，就是没传回来。请问这个怎么处理呀。
> 
> ·超时问题：首先在discord输入/info查看你的Fast Time Remaining快速出图时间，然后我了解到有些朋友的是某宝某鱼上租的共享账号，这类账号的特点问题就是人多使用，加上上面的快速出图时间可能用完了，造成了你提交的作图一直在排队中，针对这类问题的解决方案如下：首先将midjourney-proxy更新到最新版，然后在他的配置项里面有一个mj.queue.timeout-minutes配置，即为任务超时时间，默认是五分钟，由于你的是多人使用的账号，所以次数可以延长些，改到十分钟甚至更长，具体自己试试，如果是专业版的话还可以修改mj.queue.core-size和mj.queue.queue-size并发数和等待队列长度，具体参考MidJourney订阅级别 https://docs.midjourney.com/docs/plans

嗯嗯，我不是这个原因，我能看到discord很快就出图了，但一直没有返回到vx。
我的账号是个人使用的，以下是我的/info信息：
Fast Time Remaining: 14.74/15.0 hours (98.29%)
Lifetime Usage: 45 images (0.69 hours)
Relaxed Usage: 0 images (0.00 hours)

**Comment by mouxangithub** [comment]
> > > > MJ代理需要用一些特殊手段进行魔法加速，国内服务器会经常提示超时，这个插件也无法解决
> > > 
> > > 
> > > 我的服务器是境外的，也会显示"任务超时"。我看了下discord前端，图片是有画出来的，就是没传回来。请问这个怎么处理呀。
> > 
> > 
> > ·超时问题：首先在discord输入/info查看你的Fast Time Remaining快速出图时间，然后我了解到有些朋友的是某宝某鱼上租的共享账号，这类账号的特点问题就是人多使用，加上上面的快速出图时间可能用完了，造成了你提交的作图一直在排队中，针对这类问题的解决方案如下：首先将midjourney-proxy更新到最新版，然后在他的配置项里面有一个mj.queue.timeout-minutes配置，即为任务超时时间，默认是五分钟，由于你的是多人使用的账号，所以次数可以延长些，改到十分钟甚至更长，具体自己试试，如果是专业版的话还可以修改mj.queue.core-size和mj.queue.queue-size并发数和等待队列长度，具体参考MidJourney订阅级别 https://docs.midjourney.com/docs/plans
> 
> 嗯嗯，我不是这个原因，我能看到discord很快就出图了，但一直没有返回到vx。 我的账号是个人使用的，以下是我的/info信息： Fast Time Remaining: 14.74/15.0 hours (98.29%) Lifetime Usage: 45 images (0.69 hours) Relaxed Usage: 0 images (0.00 hours)

如果是mj-proxy接口文档提示超时的话你可以尝试设置mj.queue.timeout-minutes
