### ISSUE TITLE
希望能添加一个每个用户画图上限的功能。

### ISSUE THREAD

**Issue by Neph0s** [mouxangithub/plugin_midjourney#8]

**Comment by mouxangithub** [comment]
已发布更新至1.0.44即可

**Comment by Neph0s** [comment]
感谢！

**Comment by ladypiapia** [comment]
请问大佬，我是通过docker compose来部署的 chat-on-wechat ，是不是就无法使用你更新的功能，因为我看不到插件目录和配置文件，不知道如何配置 daily_limit，不能在微信中直接直接设置daily_limit这个配置项哈？ @mouxangithub

**Comment by mouxangithub** [comment]
> 请问大佬，我是通过docker compose来部署的 chat-on-wechat ，是不是就无法使用你更新的功能，因为我看不到插件目录和配置文件，不知道如何配置 daily_limit，不能在微信中直接直接设置daily_limit这个配置项哈？ @mouxangithub

docker compose也是有目录文件的，在容器目录下的app里面就是chat-on-wechat的项目目录，然后其他的就基本上一样，目前倒是也支持指令修改，不过不会重置已经生效的limit，后续会更新一个版本修改后重置

**Comment by mouxangithub** [comment]
> 

没设置热更新的话可以指令修改完limit，然后重启chat-on-wechat服务试试

**Comment by ladypiapia** [comment]
> 

指令是啥？#daiy_limit 和 $daily_limit 都试了

**Comment by ladypiapia** [comment]
> > 
> 
> 指令是啥？#daiy_limit 和 $daily_limit 都试了

在代码里找到了，是`$s_limit`
